import type { MoniconConfig } from "@monicon/core";
import { iconsGenPlugin } from "./monicon-config/iconsGenPlugin.ts";

export default {
	icons: getIconsArray(),
	plugins: [iconsGenPlugin({ outputPath: ".monicon" })],
} satisfies MoniconConfig;

function getIconsArray() {
	return [
		"radix-icons:chevron-down",
		"lucide:chevron-down",
		"lucide:chevron-up",
		"lucide:check",
		"lucide:circle-check",
		"lucide:chevron-down",
		"radix-icons:dash",
		"radix-icons:dot-filled",
		"radix-icons:chevron-right",
		"lucide:panel-left",
		"lucide:x",
		"lucide:arrow-left",
		"lucide:arrow-right",
		"lucide:arrow-up",
		"lucide:archive",
		"lucide:book-user",
		"lucide:calendar-clock",
		"lucide:calendar-x",
		"radix-icons:check",
		"lucide:chevron-left",
		"lucide:chevron-right",
		"lucide:chevrons-up-down",
		"lucide:clipboard-list",
		"lucide:clock",
		"lucide:crown",
		"lucide:dollar-sign",
		"lucide:download",
		"lucide:ellipsis",
		"lucide:eye",
		"lucide:eye-off",
		"lucide:file-down",
		"lucide:filter",
		"lucide:layout-dashboard",
		"lucide:link",
		"lucide:list-filter",
		"lucide:log-out",
		"lucide:mail",
		"lucide:minus",
		"lucide:package-x",
		"lucide:pencil",
		"lucide:search",
		"lucide:search-x",
		"lucide:send",
		"lucide:bell",
		"lucide:settings",
		"lucide:shield",
		"lucide:shield-check",
		"lucide:shopping-cart",
		"lucide:trash-2",
		"lucide:trending-down",
		"lucide:triangle-alert",
		"lucide:user",
		"lucide:user-check",
		"lucide:user-cog",
		"lucide:user-round",
		"lucide:user-round-x",
		"lucide:users",
		"lucide:users-round",
		"lucide:wallet",
		"lucide:zap",
		"lucide:zap-off",
		"lucide:plus",
		"lucide:circle",
		"lucide:refresh-cw",
		"devicon:google",
		"mingcute:check-circle-fill",
		"material-symbols:mail",
		"material-symbols:troubleshoot",
		"streamline:padlock-square-1-solid",
		"material-symbols:dashboard-outline-rounded",
		"material-symbols:dashboard-rounded",
		"material-symbols:inventory-2-outline-rounded",
		"material-symbols:inventory-2-rounded",
		"mdi:chart-box-outline",
		"mdi:chart-box",
		"material-symbols:warning-outline",
		"material-symbols:warning-rounded",
		"material-symbols:settings-outline-rounded",
		"material-symbols:settings-rounded",
		"material-symbols:error-outline-rounded",
		"lucide:send-horizontal",
		"solar:file-outline",
		"solar:document-medicine-linear",
	];
}
