export {
	backendApiSchema,
	backendApiSchemaRoutes,
	SignUpSchema,
	StockAdditionLogTypeSchema,
	StockLogTypeSchema,
	StockMovementLogTypeSchema,
	StockOutReasonSchema,
	StockReductionLogTypeSchema,
	WorkspaceRoleSchema,
	type BackendApiRouteKeys,
	type BackendApiRoutes,
	type BaseApiErrorResponse,
	type BaseApiSuccessResponse,
} from "@vitastock/shared/validation/backendApiSchema";
